version: "3.3"
services:
  database:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: crypto-trader
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: crypto-trader-db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
      - ./docker/mysql/data:/var/lib/mysql
  crypto-trader:
    build: .
    restart: unless-stopped
    ports:
      - "9010:9010"
    environment:
      CLIENT_SECRET: ${CLIENT_SECRET}
      CLIENT_ID: ${CLIENT_ID}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_RECIPIENTS: ${EMAIL_RECIPIENTS}
      DATABASE_HOST: ${DATABASE_HOST:-database}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_URL: ${DATABASE_URL:-jdbc:mysql://database:3306/crypto-trader-db}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-crypto-trader}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}
      JAVA_OPTIONS: ${JAVA_OPTIONS:-}