spring.jpa:
  show-sql: false
  hibernate.ddl-auto: update
spring.main.web-application-type: none
logging.level:
  org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
  com.github.marceloleite2604.cryptotrader: DEBUG

mercado-bitcoin:
  base-uri: https://api.mercadobitcoin.net/api/v4/
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
mail:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  host: ${EMAIL_HOST}
  port: ${EMAIL_PORT}
  recipients: ${EMAIL_RECIPIENTS}
database:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: ${DATABASE_URL}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  connections: 4